In [1]:
import numpy as np
import pandas as pd
pd.options.display.max_columns = 20
pd.options.display.max_rows = 20
pd.options.display.max_colwidth = 80
np.set_printoptions(precision=4, suppress=True)

In [2]:
data = [np.random.standard_normal() for i in range(7)]
print(data)

[2.697568002854463, -0.8222981710851884, -2.384571409996956, 0.273726270568689, -1.193828907329313, 0.27423153233605496, 0.6147762016195892]


In [3]:
data

[2.697568002854463,
 -0.8222981710851884,
 -2.384571409996956,
 0.273726270568689,
 -1.193828907329313,
 0.27423153233605496,
 0.6147762016195892]

In [4]:
data?

Type:        list
String form: [2.697568002854463, -0.8222981710851884, -2.384571409996956, 0.273726270568689, -1.193828907329313, 0.27423153233605496, 0.6147762016195892]
Length:      7
Docstring:  
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.

--------------------Tuples

In [5]:
tup = (4, 5, 6)
tup

(4, 5, 6)

In [6]:
tup2 = tuple([4, 0, 2])
tup2

(4, 0, 2)

In [7]:
tup3 = tuple('string')
tup3

('s', 't', 'r', 'i', 'n', 'g')

In [8]:
nested_tuples = (4, 5, 6), (7, 8)
#nested_tuples
#nested_tuples[0]
nested_tuples[0][0]

4

--------------------List

In [9]:
gen = range(10)
gen

range(0, 10)

In [10]:
list(gen)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
a_list = [1, 2, 3, 4, 5]
a_list

[1, 2, 3, 4, 5]

In [12]:
a_list.append(10)
a_list

[1, 2, 3, 4, 5, 10]

In [13]:
a_list.insert(1, 20)
a_list

[1, 20, 2, 3, 4, 5, 10]

In [14]:
a_list.pop(2)
a_list

[1, 20, 3, 4, 5, 10]

In [15]:
20 in a_list

True

In [16]:
b_list = [5, 8, 9, 2, 5, 1]
b_list

[5, 8, 9, 2, 5, 1]

In [17]:
b_list.sort()
b_list

[1, 2, 5, 5, 8, 9]

--------------------Numpy

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
samples = np.random.standard_normal(size=(4,4))
samples

array([[ 1.2215, -0.7305,  0.0122,  1.6093],
       [ 0.0508, -0.0663, -0.9192, -0.342 ],
       [-0.6615, -0.0777, -0.2467,  1.1304],
       [-0.3207, -1.0921,  0.7456, -1.4144]])

In [22]:
np.maximum(samples, samples/2)

array([[ 1.2215, -0.3653,  0.0122,  1.6093],
       [ 0.0508, -0.0332, -0.4596, -0.171 ],
       [-0.3308, -0.0389, -0.1233,  1.1304],
       [-0.1603, -0.546 ,  0.7456, -0.7072]])

--------------------Pandas

In [23]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [24]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [25]:
obj.index = ["Bob", "Steve", "Jeff", "Ryan"]
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [26]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [27]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [28]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [29]:
obj3.reindex(np.arange(6), method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [30]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), index=["a", "c", "d"], columns=["Ohio", "Texas", "California"])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [31]:
frame2 = frame.reindex(index=["a", "b", "c", "d"])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [32]:
states = ["Ohio", "Texas", "Utah", "California"]
frame.reindex(columns=states)

Ohio  Texas  Utah  California
a     0      1   NaN           2
c     3      4   NaN           5
d     6      7   NaN           8

#LOC

In [33]:
frame.loc[["a", "d", "c"], ["California", "Texas"]]

California  Texas
a           2      1
d           8      7
c           5      4

In [36]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [37]:
new_obj = obj.drop("c")
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [38]:
obj.drop(["d", "c"])

a    0.0
b    1.0
e    4.0
dtype: float64

In [41]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), index=["Ohio", "Colorado", "Utah", "New York"], columns=["one", "two", "three", "four"])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [42]:
data.drop(index=["Colorado", "Ohio"])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [43]:
data.drop(columns=["two"])

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15